# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".gitignore"
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v50.0.0

  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - run: |
          # Workaround for https://github.com/canonical/charmcraft/issues/1389#issuecomment-1880921728
          touch requirements.txt
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.7.0
        continue-on-error: true
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-labels: false
          fail-build: ${{ github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write

  promtool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      # prometheus snap includes promtool
      - name: Install prometheus snap
        run: sudo snap install prometheus

      - name: Check validity of prometheus alert rules
        run: |
          promtool check rules src/alert_rules/prometheus/*.yaml

  build:
    strategy:
      matrix:
        path:
          - .
          - tests/integration/dashboards_application_charm
          - tests/integration/dashboards_tester_charm
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v50.0.0
    with:
      cache: false
      path-to-charm-directory: ${{ matrix.path }}

  integration-test:
    name: Integration test charm
    needs:
      - lint
      - build
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets: inherit
    permissions:
      contents: write # Needed for Allure Report
